on: [push, pull_request]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GHA_PAT }}
    
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: Lint
        run: |
          out <- 
            lintr::lint_package(
              linters = lintr::linters_with_defaults(
                object_usage_linter = NULL,
                trailing_whitespace_linter = NULL,
                cyclocomp_linter = NULL
              ),
            exclusions = c(
              list.files("tests", recursive = TRUE, full.names = TRUE),
              list.files("man", recursive = TRUE, full.names = TRUE),
              list.files("vignettes", recursive = TRUE, full.names = TRUE),
              list.files("data-raw", recursive = TRUE, full.names = TRUE),
              list.files("inst", recursive = TRUE, full.names = TRUE)
            )
          )
          print(out)
          if (length(out)) stop("lints found")
        shell: Rscript {0}
